config/routes.rb
Rails.application.routes.draw do
  resources :company_groups
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/company_group.rb
class CompanyGroup < ApplicationRecord

  validates :name, presence: true
  validates_uniqueness_of :name


  has_ancestry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/company_groups_controller.rb
class CompanyGroupsController < ApplicationController
  before_action :set_company_group, only: [:show, :edit, :update, :destroy]

  # GET /company_groups
  # GET /company_groups.json
  def index
    @company_groups = CompanyGroup.all
    @hashs = CompanyGroup.all
    @tests = CompanyGroup.all
    @others = CompanyGroup.all
    @anothers = CompanyGroup.all
  end

  # GET /company_groups/1
  # GET /company_groups/1.json
  def show
      @company_groups = CompanyGroup.all
  end

  # GET /company_groups/new
  def new
    @company_groups = CompanyGroup.all
    @company_group = CompanyGroup.new
  end

  # GET /company_groups/1/edit
  def edit
      @company_groups = CompanyGroup.all
  end

  # POST /company_groups
  # POST /company_groups.json
  def create
    @company_groups = CompanyGroup.all
    @company_group = CompanyGroup.new(company_group_params)

    respond_to do |format|
      if @company_group.save
        format.html { redirect_to company_groups_path, notice: 'Company group was successfully created.' }
        format.json { render :show, status: :created, location: @company_group }
      else
        format.html { render :new }
        format.json { render json: @company_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /company_groups/1
  # PATCH/PUT /company_groups/1.json
  def update
    @company_groups = CompanyGroup.all
    respond_to do |format|
      if @company_group.update(company_group_params)
        format.html { redirect_to company_groups_path, notice: 'Company group was successfully updated.' }
        format.json { render :show, status: :ok, location: @company_group }
      else
        format.html { render :edit }
        format.json { render json: @company_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /company_groups/1
  # DELETE /company_groups/1.json
  def destroy
    @company_group.destroy
    respond_to do |format|
      format.html { redirect_to company_groups_url, notice: 'Company group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_company_group
      @company_group = CompanyGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def company_group_params
      params.require(:company_group).permit(:name, :father_group, :parent_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/company_groups_helper.rb
module CompanyGroupsHelper
end

app/views/company_groups/_form.html.erb
<%= form_with(model: company_group, local: true) do |form| %>
  <% if company_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(company_group.errors.count, "error") %> prohibited this company_group from being saved:</h2>

      <ul>
      <% company_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :father_group %>
    <%= form.select :father_group, @company_groups.collect { |company_group| [company_group.name, company_group.id] } %>
  </div>

  <div class="field">
    <%= form.label :parent_id %>
    <%= form.select :parent_id, options_from_collection_for_select(@company_groups, "id", "name") %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/company_groups/edit.html.erb
<h1>Editing Company Group</h1>

<%= render 'form', company_group: @company_group %>

<%= link_to 'Show', @company_group %> |
<%= link_to 'Back', company_groups_path %>

app/views/company_groups/index.html.erb
<p id="notice"><%= notice %></p>
<div class="container">
  <h1>Company Groups</h1>
  <button type="button" class="btn btn-dark" style="margin-top: 30px;"><%= link_to 'Criar novo CompanyGroup', new_company_group_path %></button>
  <table style="margin-top: 30px;">
    <thead>
      <tr class="paddingg text-center">
        <th class="paddingg">ID</th>
        <th class="paddingg">Nome</th>
        <th class="paddingg">Grupo Pai</th>
        <th class="paddingg">Parent ID</th>
        <th colspan="3" class="paddingg">Ações</th>
      </tr>
    </thead>

    <tbody>
      <% @company_groups.each do |company_group| %>
      <tr class="paddingg text-center">
        <td class="paddingg"><%= company_group.id %></td>
        <td class="paddingg"><%= company_group.name %></td>
        <td class="paddingg"><%= company_group.father_group %></td>
        <td class="paddingg"><%= company_group.parent_id %></td>
        <td class="paddingg"><%= link_to 'Ver', company_group %></td>
        <td class="paddingg"><%= link_to 'Editar', edit_company_group_path(company_group) %></td>
        <td class="paddingg"><%= link_to 'Destruir', company_group, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      <% end %>
    </tbody>
  </table>

  <% @company_groups.each do |company_group| %>
    <h1> <% company_group.subtree_ids %> </h1>

  <% end %>


  <ul class="nav nav-tabs" style="margin-top: 30px;">
    <% @company_groups.each do |company_group| %>
    <li><a data-toggle="tab" href="#<%= company_group.name %>"> <%= company_group.name %> , <%= company_group.id %> </a></li>
    <% end %>
  </ul>

  <div class="tab-content">
    <% @company_groups.each do |company_group| %>

    <div id="<%= company_group.name %>" class="tab-pane fade">
      {
        <p>{id:<%= company_group.id %>, nome:<%= company_group.name %>, grupo_pai:<%= company_group.father_group %>},</p>
        <% @hashs.each do |hash| %>
        <% if hash.father_group == company_group.id %>
        <p>{id:<%= hash.id %>, nome:<%= hash.name %>, grupo_pai:<%= hash.father_group %>},</p>
        <% @tests.each do |test| %>
        <% if test.father_group == hash.id%>
        <p>{id:<%= test.id %>, nome:<%= test.name %>, grupo_pai:<%= test.father_group %>},</p>
        <% @others.each do |other| %>
        <% if other.father_group == test.id%>
        <p>{id:<%= other.id %>, nome:<%= other.name %>, grupo_pai:<%= other.father_group %>},</p>
        <% @anothers.each do |another| %>
        <% if another.father_group == other.id%>
        <p>{id:<%= another.id %>, nome:<%= another.name %>, grupo_pai:<%= another.father_group %>},</p>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
        <% end %>
      }
    </div>
    <% end %>
  </div>

</div>

<br>

app/views/company_groups/new.html.erb
<h1>New Company Group</h1>

<%= render 'form', company_group: @company_group %>

<%= link_to 'Back', company_groups_path %>

app/views/company_groups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @company_group.name %>
</p>


<ul id="menu">
  {
  <% @company_group.subtree.each do |company_group| %>

      <p>{id:<%= company_group.id %>, nome:<%= company_group.name %>, grupo_pai:<%= company_group.parent_id %>},</p>

  <% end %>
}
</ul>

<%= link_to 'Edit', edit_company_group_path(@company_group) %> |
<%= link_to 'Back', company_groups_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Dtidigital</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.0/js/bootstrap.min.js"></script>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= yield %>
</body>
</html>